# -*- coding: utf-8 -*-
"""Aula 02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17pzg-Xw1LHKEtpU6i-8ftCMxGhwmwv1j
"""



#Exercicio 02
num1 = int(input("Digite seu número: "))
num2 = int(input("Digite seu número: "))
soma = num1 - num2
print("O resultado será:", soma)

#Exercicio 03
num1 = int(input("Digite seu número: "))
num2 = int(input("Digite seu número: "))
soma = num1 + num2
print("O resultado será:", soma)


#Exercicio 03
num1 = int(input("Digite seu número: "))
num2 = int(input("Digite seu número: "))
soma = num1 - num2
print("O resultado será:", soma)

#Exercicio 03
num1 = int(input("Digite seu número: "))
num2 = int(input("Digite seu número: "))
soma = num1 * num2
print("O resultado será:", soma)

#Exercicio 03
num1 = int(input("Digite seu número: "))
num2 = int(input("Digite seu número: "))
soma = num1 / num2
print("O resultado será:", soma)

#Exercicio 04
nome = input("Qual o seu nome?")
print("Olá! Seja Bem vindo!",nome)

